import { loadFile, mount, reactive, whenReady } from "@odoo/owl";
import App from './App'
import { nokia3210 } from "./displays/Displays";

whenReady(async function () {

  const [templates, cpp_content] = await Promise.all([
    loadFile("templates.xml"),

    // loadFile("examples/intro.raw.cpp"),
    // loadFile("examples/dev1.cpp"),
    loadFile("examples/dev_nokia_3210.cpp"),
  ])

  const env = {
    editor: reactive({
              content: cpp_content,
              editLine: ()=>{}, //changed later by Editor
              getFunctionParameter: ()=>{}, //changed later by Editor
            }),
    sim: reactive({
          display: nokia3210,
          display_name: nokia3210.name,
          scale:6,
          layers: [], //generated by loop are duplicated
          lines: [], //layers, unique per-line-number
          })
  }

  mount(App, document.body, { 
      env, 
      templates, 
      // 'debug': true,
      //props: {...}, templates: "..."}
  });
  
})
